# Generated by Django 2.2.3 on 2019-07-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190711_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskTest',
        ),
    ]
