# Generated by Django 2.2.3 on 2019-07-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190711_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTest',
            new_name='Task',
        ),
    ]
